### ISSUE TITLE
bpython? Anyone?

### ISSUE THREAD

**Issue by grafa** [timofurrer/try#7] opened 2016-03-26 07:10 UTC
Hi there,

thanks for awesome package.

Do you tink it's possible to add support for bpython? It's much better then ipython and I think many people would appreciate this.

Thanks in advance.

**Comment by timofurrer** [comment] 2016-03-26 18:57
Duplicate of #5

**Comment by timofurrer** [comment] 2016-03-26 23:30
I've implemented a `--shell` option:

`try requests --shell bpython`

It's been released with versoin `0.1.6`! Have fun!

**Closed by timofurrer** 2016-03-26 23:30 UTC

**Comment by grafa** [comment] 2016-03-28 19:06
Awesome job done there!But I'm getting an error...

I've updated via pip install -U. Current version is 0.2.2.

```shell
grafa@tp ~> try requests --shell bpython
Traceback (most recent call last):
  File "/usr/local/bin/try", line 7, in <module>
    from trypackage.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/trypackage/__main__.py", line 59, in <module>
    @click.command(context_settings=dict(default_map=parse_config(os.path.join(click.get_app_dir("try"), "config.ini"))))
  File "/usr/local/lib/python2.7/dist-packages/trypackage/config.py", line 32, in parse_config
    "python": parser.get("env", "python", fallback=None),
TypeError: get() got an unexpected keyword argument 'fallback'
```

Thanks

**Comment by timofurrer** [comment] 2016-03-28 20:13
Looks like `fallback` argument is not supported in python 2.7. I'll fix this as soon as possible.
In the meantime I suggest you to install `try` with `pip3` or just in a python 3.4+ environment:

```
sudo pip uninstall try
sudo python3.4 -m pip install try -U
```

**Comment by grafa** [comment] 2016-04-02 07:59
Yea, that works. Thank you.

Looking forward to see 2.7. working again!

**Comment by timofurrer** [comment] 2016-04-03 06:30
Can you try if version `0.2.3` works for you?

**Comment by grafa** [comment] 2016-04-03 08:43
Yes! Great work mate.
